### ISSUE TITLE
Error: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by atomantic** [stdlib/lib#33]
function runs fine locally but when I publish `dev` or `release`, I get an error.

`f .` => `incubated cross-platform applications`
`f . 2` => `mesh 24/7 programming, liberating orchestrated collaborative touchpoints`

`lib up dev`
```
...
Functions available:

  antic/buzz@dev/buzz
    Function

      [0] iterations
```

`f antic/buzz@dev/buzz`

```
Error: Error: Cannot read property 'filename' of undefined
    at IncomingMessage.<anonymous> (/Users/antic/.nvm/versions/node/v6.9.1/lib/node_modules/lib/node_modules/f/lib/f.js:100:27)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

https://f.stdlib.com/antic/buzz
```
Error: Cannot read property 'filename' of undefined
```

**Comment by keithwhor** [comment]
Hey, can't get to this for a little bit, but if you join our Slack and ping me directly there I can help you with this. I'll need to look at the code you're trying to push. Link is on the main website :).
- Keith

**Comment by keithwhor** [comment]
The issue is with the `buzzphrase` module itself. There's a line containing `require.main.filename` and a comparator, and `require.main` is not "safe" in and of itself, there's no "main module" within the microservice while it's executing. We can shim this behavior in if it brings up additional issues, but I also recommend (as you're the owner of the `buzzphrase` module) that a quick fix is to ensure `require.main` is defined (/exists) before you compare it to anything. A simple line change in the underlying package should enable your service to run without issue. :)

```
(require.main || {}).filename === [...]
```

Cheers!

**Comment by atomantic** [comment]
Hah! that's what I get for working on this on a sick day. Thanks for finding that. Fixed and deployed. Looks great :)

**Comment by keithwhor** [comment]
No worries! If you want to remove the broken version from the registry you can do `$ lib down -r <version>` :).
