### ISSUE TITLE
Logging and monitoring

### ISSUE THREAD

**Issue by tonyxiao** [stdlib/lib#53]
I can't seem to find any documentation on how logging and monitoring works with lib. Can someone point me in the right direction there?

**Comment by keithwhor** [comment]
Hey Tony! Right now you'll have to use a third-party solution for logging within a function call after it's deployed (though local logging should work just fine).

This might sound silly (slash ultra hacky), but our team has been hacking it out by using `lib.utils.sms()` (https://stdlib.com/utils/sms) and texting ourselves results if necessary. We're building out a more sustainable solution that should be available in the next month. We'd love feedback as to what you're looking for in a logging solution, because there's a lot to build.

**Comment by tonyxiao** [comment]
Haha that's hilarious. I think it'd be awesome if you can maybe setup an example of integrating with say LogDNA / DataDog in a function repo so people can copy / follow

**Comment by jacoblee93** [comment]
@tonyxiao we recently launched a logging service, check it out here: http://stdlib.com/utils/log

**Comment by tonyxiao** [comment]
Oh this is really awesome! Are there metrics / monitoring available? How many requests per second is a function getting, is it returning errors? Also are logs split by invocations of the function or just all aggregated in one place?

**Comment by keithwhor** [comment]
A lot of this data you can view on our dashboard: https://dashboard.stdlib.com/dashboard/

Data refreshes every ~10 minutes or so. :)
