### ISSUE TITLE
Format documentation with StandardJS

### ISSUE THREAD

**Issue by adius** [stdlib/lib#86]
https://standardjs.com is nowadays the most popular way to format JavaScript.
Therefore I think you should format your code examples accordingly, to make it easier and more familiar to read for most JavaScript developers.

**Comment by keithwhor** [comment]
Hey @adius!

I'm not opposed to this, we should at the very least use `prettier`. I love semicolons and I have a personal style I like, but there's an argument to be made for Standard style, certainly.

I can talk with the team about this: it's not a top priority, so don't be surprised if it takes a little while - I don't think semicolons make things less readable, so I'll give pushback there, but otherwise, solid ask.

**Comment by adius** [comment]
Yeah I love semicolons. There is nothing better than useless characters in code. That's why I tend to write my code like this: 

```js
;;;;;;;;;;
function add (first, second) {;;;;;;;;;;
  return first + second;;;;;;;;;;
};;;;;;;;;;
;;;;;;;;;;
add(5, 10);;;;;;;;;;
;;;;;;;;;;
```

It really makes things a lot more readable. It's quite amazing!

;-)

**Comment by keithwhor** [comment]
Hey, I understand you're making a joke but we're taking this seriously and would prefer if comments in issues are productive.

Nothing against you, just want to set policy. Thanks for understanding :)! We'll get to this when we can.

**Comment by adius** [comment]
I'm not joking. I'm dead serious that using semicolons in JavaScript is really ridiculous.
Your code contains numerous lines where you forgot to put the semicolon (e.g. https://github.com/stdlib/lib/blob/master/cli/config.js#L49), which is totally understandable as it literally makes no difference.

I just can't wrap my head around why one would bother to put useless characters into their code.
Nothing against you, I just wholeheartedly hate semicolons. ;-)

**Comment by keithwhor** [comment]
Hey Adrian - thanks for the input. We heard you loud and clear with the first ask. If you'd like to submit a PR that uses `prettier` to format the codebase without semicolons, you're free to do so and we'll gladly review it. Otherwise updates to style changes will be on our timeline. I've closed the issue as we understand what you're requesting and we've listed it as a todo internally.

Cheers and thanks for understanding!
- Keith
